elf: Add support for map struct typedef
cilium/ebpf pull request #1125
Opened 2023-08-31 11:16 UTC by anjmao

Fixes https://github.com/cilium/ebpf/issues/1126

2023-09-11 14:27 UTC, lmb requested changes
Does this work with `libbpf`?

2023-09-11 14:27 UTC, lmb commented on elf_reader.go
>  			mapStruct, ok := v.Type.(*btf.Struct)
I think using https://pkg.go.dev/github.com/cilium/ebpf/btf#UnderlyingType here is more appropriate.

2023-09-12 06:51 UTC, anjmao commented
> Does this work with `libbpf`?

Yes, typedefs are used in some tracee ebpf code places. It uses libbpf and libbpfgo cgo wrapper. It's great that this was the only needed change to migrate such large ebpf code base to cilium/ebpf.

2023-09-12 09:42 UTC, lmb commented
I forgot: can you add a test in `loader.c` for this behaviour?

2023-10-10 12:46 UTC, merged