Add Remaining and Size to perf/ring Record
cilium/ebpf pull request #1167
Opened 2023-10-16 19:06 UTC by brycekahle

This allows tracking utilization of the underlying buffers. Processing the values to make sense in a user's monitoring system is left to the user. 

Using the post-read remaining bytes allows the value to reach zero, whereas a pre-read value would never reach zero.

2023-10-18 10:22 UTC, lmb requested changes
Looks good, can you add test coverage please?

2023-10-18 21:22 UTC, brycekahle commented on perf/reader.go
> +	Remaining int
Updated

2023-10-18 21:24 UTC, brycekahle commented on perf/reader.go
> +	Size int
The size we are interested in, is the data portion, without the metadata page. Moving the call to `perfBufferSize` would've required changes to a bunch of other places that expect `newPerfEventRing` to handle the size manipulation. I did something different, let me know what you think.

2023-10-18 21:25 UTC, brycekahle commented
> Looks good, can you add test coverage please?

Added. For the backward/overwriteable buffer it isn't possible to get a precise remaining count once it has been overwritten.

2023-10-19 10:18 UTC, lmb commented on perf/reader.go
> +func (pr *Reader) Size() int {
I think your `bufferSize` idea is better:

```suggestion
func (pr *Reader) BufferSize() int {
```

2023-10-19 19:10 UTC, brycekahle commented
> Should we just set remaining to `-1` for now in that case and document that this means the data remaining can't be determined?

We could. It does work correctly until any kind of overwrite happens, and then it becomes inaccurate by reporting more data remaining than their actually is (because of the partial leftover records).

2023-10-20 11:13 UTC, lmb approved these changes
Pushed a doc fix. Please squash then we are good to go.

2023-10-20 16:53 UTC, brycekahle commented
squashed

2023-10-24 08:45 UTC, merged