Add support to retrieve missed counts from probes
cilium/ebpf pull request #1295
Opened 2024-01-05 14:25 UTC by olsajiri

wip

2024-02-16 10:13 UTC, rgo3 requested changes
I've reviewed this PR with Lorenz yesterday and we concluded that we might need to figure out a better way of dealing with the `bpf_link_info` UAPI in ebpf-go before your proposed changes can be implemented. I've pointed out two specific problems in the PR where we hope a better UAPI representation will enable better solutions to retrieve and write metadata on `LinkInfo` objects. Lorenz and I will spend an hour today to see what we can come up with.

2024-02-16 11:16 UTC, rgo3 commented
I will spend some more time next week to work on the ideas Lorenz had to change how ebpf-go represents the `bpf_link_info` struct in Go.

2024-02-17 13:09 UTC, olsajiri commented
> I will spend some more time next week to work on the ideas Lorenz had to change how ebpf-go represents the `bpf_link_info` struct in Go.

sounds great, please let me know if I can help in any way

2024-03-28 14:42 UTC, olsajiri commented
@lmb @rgo3 hey guys, could you plz check on the new changes?
I rebased that on the latest and it works now with tetragon https://github.com/cilium/tetragon/pull/1941 thanks

2024-04-02 14:11 UTC, lmb requested changes
I pushed some fixups in order to get this merged quickly. Main changes:

* We can't just return ErrNotSupported. Instead I added getters on `KprobeInfo` which allow the caller to detect whether we could get the info from the kernel. This is how `MapInfo` and `ProgramInfo` work already.
* Add `sys.PerfEventLinkInfo` and clean up usage. Yes, another syscall. I've outlined the way to fix this in Robin's last PR. The current approach is cheating and will have to change as soon as the next perf event info thingie lands.

Please take a look, and let me know whether you're OK with dropping exporting the new constants from package link.

2024-04-03 13:21 UTC, olsajiri commented on internal/sys/types.go
> +	FuncName      uint64
ok

2024-04-03 13:21 UTC, olsajiri commented on internal/sys/types.go
> +	Addrs  uint64
ok

2024-04-03 13:22 UTC, olsajiri commented on link/link.go
> +	Addr   uint64
ok

2024-04-03 13:22 UTC, olsajiri commented on link/link.go
> +func (r *PerfEventInfo) Kprobe() *KprobeInfo {
ok

2024-04-03 13:27 UTC, olsajiri commented on link/link.go
> +			return nil, fmt.Errorf("kprobe multi link info: %w", ErrNotSupported)
ok

2024-04-04 13:38 UTC, lmb commented on link/syscalls.go
> +	UnspecifiedPerfEventInfoType = sys.BPF_PERF_EVENT_UNSPEC
You need to add dummy entries to https://github.com/cilium/ebpf/blob/main/internal/unix/types_other.go

2024-04-04 13:40 UTC, lmb commented on link/link.go
> +	"golang.org/x/sys/unix"
```suggestion
	github.com/cilium/ebpf/internal/unix"
```

2024-04-05 08:26 UTC, lmb commented
@olsajiri good to go?

2024-04-05 08:26 UTC, olsajiri commented on link/syscalls.go
> +	UnspecifiedPerfEventInfoType = sys.BPF_PERF_EVENT_UNSPEC
hum, I ended up using BPF_PERF_EVENT_x consts from internal/sys/types.go , seems to work

2024-04-05 08:28 UTC, olsajiri commented
@lmb yes, I have tetragon changes on top of this and it looks good, so looks good to me

2024-04-09 09:18 UTC, lmb approved these changes
Renamed `MultiInfo.Addresses` to `MultiInfo.AddressCount`.

2024-04-09 11:05 UTC, merged