btf/cmd/genbtftypes: (#1218) a generator that generates btf_types.go
cilium/ebpf pull request #1304
Opened 2024-01-10 22:12 UTC by OmarTariq612

This is guaranteed to match the kernel struct defenitions.

I've tried to generate those structs in the `sys` package (`sys/types.go`) but there are private methods so I've tried to write those method manually after generating the types but there were other dependencies (constants like `btfMagic`, types like `FwdKind`).

2024-01-12 08:36 UTC, ti-mo commented
@OmarTariq612 What's the benefit of having these be auto-generated? This adds 10x the amount of code to maintain to generate a handful of structs with a few fields, and these rarely change. I think @lmb's comment in the issue was just about moving the struct definitions into `sys`, not auto-generating them. Not all code in `sys` is autogenerated.

2024-01-12 13:36 UTC, lmb requested changes
Hi @OmarTariq612, thanks for your PR :) Contrary to what Timo says, I did mean to auto generate the types. I think he has a point that having a separate binary to do the generation is not necessary.

The code to generate the types can just live in `gentypes`, and the generated types can be move to and exported from `internal/sys` instead of `btf`. The btf types can just go into `sys/types.go` as well. Is that something you're up for?

2024-01-17 11:09 UTC, OmarTariq612 commented
I closed the PR by mistake, I'm still working on this, and I will reopen it when I'm done

2024-01-17 12:04 UTC, OmarTariq612 commented
@ti-mo the migration is not easy, generating those types in `internal/sys` forces us to implement the methods there and those methods depend on (ex: `btf.FwdKind`, `internal.DiscardZeroes`, ...), trying to use those from `internal/sys` introduces a cycle.

2024-01-17 12:05 UTC, OmarTariq612 commented
@ti-mo the migration is not easy, generating those types in `internal/sys` forces us to implement the methods there and those methods depend on (ex: `btf.FwdKind`, `internal.DiscardZeroes`, ...), trying to use those from `internal/sys` introduces a cycle.

2025-05-07 14:39 UTC, closed without merging