Add support to test update library with local kernel
cilium/ebpf pull request #1306
Opened 2024-01-13 20:55 UTC by olsajiri

Adding support to update update library with local kernel by passing local directory through KERNEL_VERSION, like:

  $ ls ../data/
  bpf_testmod.ko  libbpf.c  vmlinux

  $ make update-kernel-deps KERNEL_VERSION=../data

This allows to test latest kernel uapi changes with ebpf/cilium library and tetragon.

2024-01-18 16:10 UTC, lmb requested changes
Makes sense, thanks for the PR. Can you also document this in https://github.com/cilium/ebpf/blob/main/docs/ebpf/contributing/index.md#updating-kernel-dependencies ?

2024-01-19 08:30 UTC, olsajiri commented on testdata/sh/update-kernel-deps.sh
> +  cp $KERNEL_VERSION/libbpf.c $tmp
I guess it's possible, but at the moment I have the kernel build on another server, so current change fits me better.. maybe we could introduce more variables to allow that? I felt like the current change is abusing bit the KERNEL_VERSION variable, but it's simple ;-)

2024-01-19 15:43 UTC, lmb commented on testdata/sh/update-kernel-deps.sh
> +  cp $KERNEL_VERSION/libbpf.c $tmp
Hm, maybe you can abuse `rsync` to get transparent copy from your build server? Basically, the usual thing would be to rsync from a local directory, but if you set your variable to `user@host:/path/to/linux` it'd slurp that over.

I don't much see the point of adding the option in a way that means extra work for the common case to be honest.

2024-01-22 14:21 UTC, olsajiri commented on testdata/sh/update-kernel-deps.sh
> +  cp $KERNEL_VERSION/libbpf.c $tmp
hum, not sure I see enough benefit in doing the rsync.. I don't think the local kernel update will happen that often.. but I'm ok to keep that change around just for my purposes, there's no need for that to be merged if it's a problem

2024-06-21 11:16 UTC, lmb commented
I think this is a bit too specific to your setup (remotely compiling kernel), sorry.

2024-06-21 11:16 UTC, closed without merging