Inflate BTF enum values
cilium/ebpf pull request #131
Opened 2020-08-28 17:42 UTC by brycekahle

Inflates BTF enum values for easier access later since the link between `Spec.rawTypes` and `Spec.types` is difficult to navigate.

2020-08-28 21:41 UTC, brycekahle commented
This is in support of #114

2020-09-01 11:07 UTC, lmb requested changes
One nit, otherwise LGTM. Thanks!

2020-09-01 11:07 UTC, lmb commented on internal/btf/types.go
> +					return nil, fmt.Errorf("can't get name for enum value %d: %w", i, err)
Nit: `%s` is probably fine here?
```suggestion
					return nil, fmt.Errorf("can't get name for enum value %d: %s", i, err)
```

2020-09-01 16:38 UTC, brycekahle commented
Updated!

2020-09-02 08:14 UTC, merged