feat(ringbuf): Add AvailableData()
cilium/ebpf pull request #1533
Opened 2024-08-05 15:36 UTC by dave-tucker

Adds AvailableData(), which is equivalent to ring__avail_data_size in libbpf.

2024-08-06 13:11 UTC, ti-mo commented
Hi @dave-tucker, could you give an example of a practical use case? A test would be nice to have as well. Thanks!

2024-08-06 16:13 UTC, dave-tucker commented
@ti-mo added some assertions to the tests to exercise this API.
Use case is for doing ring buffer tuning work. For example, you may have [some logic in your bpf program](https://github.com/torvalds/linux/blob/eb5e56d1491297e0881c95824e2050b7c205f0d4/tools/testing/selftests/bpf/progs/ringbuf_bench.c#L23-L32) that decides whether to use `BPF_RB_NO_WAKEUP` or `BPF_RB_FORCE_WAKEUP` in `bpf_ringbuf_submit`

By periodically calling `AvailableData()` we can see from userspace how far ahead the producer is from the consumer and whether we're at risk of the ringbuf "wrapping around" and overwriting unread records.

2024-08-06 18:43 UTC, florianl approved these changes

2024-08-06 18:49 UTC, brycekahle commented
Does #1167 accomplish what you need?

2024-08-07 10:55 UTC, dave-tucker commented
@brycekahle I can try it out and compare both.
The difference between the two approaches is that `record.Remaining` is calculated once every time a record is read.
`AvailableData()` will always show the difference between the consumer/producer values at any point in time, so it would handle the case of the producer pointer increasing since last read, but we haven't been woken up to read an event yet.

2024-08-07 15:06 UTC, dave-tucker commented
> @brycekahle I can try it out and compare both.

I tried it out.

- `AvailableData` was really easy to wire up to a `prometheus.GaugeFunc` as it easily be queried once every scrape interval.
- `Record.Remaining` was less easy. I used a `prometheus.Guage` and `Set` the value within my ringbuf reading function after a record was read.

You can see this on the graphs below - Top is `AvailableData()`, Bottom is `Record.Remaining`
<img width="744" alt="Screenshot 2024-08-07 at 14 35 42" src="https://github.com/user-attachments/assets/a0ff0ba5-9314-4b33-8cef-efa9cf760f0f">

The gap in the middle was when I restarted my process to only use `BPF_RB_FORCE_WAKEUP` when there are 10 entries in the ringbuffer - each entry is 80 bytes.

The top graph is more useful for my purposes of evaluating what ☝️ does to the ring buffer.

I find the bottom graph less useful for my purposes right now, but thinking it through it might be better suited to creating a histogram.

TL;DR I think both are useful

2024-08-08 14:36 UTC, lmb requested changes
Thanks for checking, very informative, especially with the graphs! You're right that putting .Remaining in a gauge isn't going to be very helpful. Did you end up trying with a histogram?

What did you decide to change based on the metrics? Increase buffer size? Wake up less frequently?

The upside of AvailableData is that it's simple to export and graph. The downside is that we can't extend the concept to `perf`, since that wraps multiple buffers. So far we've always tried to keep the API of both packages very similar, but that is not a deal breaker.

Left some nits, overall I agree with Florian that this is fine to merge.

2024-08-08 14:36 UTC, lmb commented on ringbuf/reader.go
> +// This is racy during ongoing operations but is still useful for overall information on how a ringbuffer is behaving.
To me this line raises more questions than it answers. "racy" implies it's somehow not safe to call? I'd probably just drop the line.

2024-08-08 14:36 UTC, lmb commented on ringbuf/reader_test.go
> +				availableData += int(math.Ceil(float64(m.size)/8)*8) + 8
Could you use `internal.Align`? ringbuf header size could also be a const?

2024-08-08 14:36 UTC, lmb commented on ringbuf/reader_test.go
> +	qt.Assert(t, qt.Equals(rd.AvailableData(), uint64(availableData)))
Could you do the following instead, for all places where you compare with a constant?
```suggestion
	qt.Assert(t, qt.Equals(rd.AvailableData(), 3* 16))
```

That way we get the constant in the output of the test failure.

2024-08-08 14:37 UTC, lmb commented on ringbuf/reader.go
> +func (r *Reader) AvailableData() uint64 {
Can you make this return `int` for consistency with the existing size related fields?

2024-08-09 11:53 UTC, dave-tucker commented
> Thanks for checking, very informative, especially with the graphs! You're right that putting .Remaining in a gauge isn't going to be very helpful. Did you end up trying with a histogram?

I played around with it and it looked promising but I ended up bailing on it because I couldn't find a satisfactory size for the buckets.

> What did you decide to change based on the metrics? Increase buffer size? Wake up less frequently?

All the above. I'm still working on it, but I plan to write up what I've learned soon and I'll share it on Slack when I'm done.

> The upside of AvailableData is that it's simple to export and graph. The downside is that we can't extend the concept to `perf`, since that wraps multiple buffers. So far we've always tried to keep the API of both packages very similar, but that is not a deal breaker.
> 
> Left some nits, overall I agree with Florian that this is fine to merge.

Addressed! Thanks!

2024-08-13 07:41 UTC, ti-mo approved these changes
@dave-tucker Thanks for the context you've provided so far! Left one nit, it's common in our lib (and in Go in general) to name functions after the unit of data they return. 'Data' is redundant, since what else would a ring buffer contain? :slightly_smiling_face: 'Bytes' would be more useful here. Thanks!

2024-08-13 07:41 UTC, ti-mo commented on ringbuf/reader.go
> +func (r *Reader) AvailableData() int {
```suggestion
func (r *Reader) AvailableBytes() int {
```

2024-08-13 16:53 UTC, dave-tucker commented
Thanks for the review and suggestions @ti-mo. I've incorporated them and force-pushed an update.

2024-08-14 15:01 UTC, ti-mo commented
Pushed a small fixup, will merge when CI is green.

2024-08-14 15:27 UTC, merged