Add uretprobe example
cilium/ebpf pull request #255
Opened 2021-03-15 18:32 UTC by ungureanuvladvictor

This adds an example on how to use `cilium/ebpf` with `bpf2go` in order to attach a uretprobe to `readline` symbol from` /bin/bash`. The functionality of the BPF code was inspired from the example https://github.com/iovisor/bcc/blob/master/tools/bashreadline.py but adapted to work with `cilium/ebpf` loader.

Signed-off-by: Vlad Ungureanu <vladu@palantir.com>

2021-03-16 10:08 UTC, lmb requested changes

2021-03-16 10:08 UTC, lmb commented on examples/uprobe/main.go
> +		_ = rd.Close()
If you wait for stopped here to close the reader you can get rid of the nested go routine.

```suggestion
		<-stopper
		_ = rd.Close()
```

2021-03-16 10:08 UTC, lmb commented on examples/uprobe/main.go
> +			binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event)
RawSample can be empty if record.LostSamples != 0.

2021-03-16 10:08 UTC, lmb commented on examples/headers/common.h
> +#define BPF_F_INDEX_MASK 0xffffffffULL
I think this is OK for now, at some point we should include `linux/bpf.h`.

2021-03-18 11:40 UTC, ti-mo approved these changes
@ungureanuvladvictor Thank you, this is very useful!

2021-03-19 04:50 UTC, ungureanuvladvictor commented
@lmb addressed your comments

2021-03-22 15:58 UTC, lmb approved these changes

2021-03-22 15:58 UTC, lmb commented
Thanks!

2021-03-22 15:58 UTC, merged