examples: added cgroup_skb example
cilium/ebpf pull request #465
Opened 2021-10-27 04:01 UTC by mingleiw

added cgroup_skb example to show how to attach the ebpf program to the socket egress to count the packets.

1. Updated the README.
2. Added cgroup_skb/bpf/cgroup_skb_example.c and examples/cgroup_skb/main.go

2021-10-29 18:24 UTC, mingleiw commented on examples/README.md
> +  * [cgroup_skb](cgroup_skb/) - Count the egress packets by attaching the program to the socket. It assumes cgroups2 file system was mounted at /sys/fs/cgroup/unified. If this is not true, run `sudo
Thanks, Lorenz. That's good to know. What does your`/proc/mounts` look like? My box is ubuntu 18.04 and /proc/mounts is look like the following:

```
$ cat /proc/mounts | grep cgroup
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
```

I modified that code a little bit and updated the pull request(check if mount[2] is cgroup2). Can you test it again on your box? Thanks!

2021-11-02 09:07 UTC, lmb commented on examples/cgroup_skb/main.go
> +var cgroup2Mount = struct {
For the example its OK to skip the `sync.Once` and memoizing the result of the lookup I think: less code in an example is better.

2021-11-02 09:07 UTC, lmb commented on examples/cgroup_skb/main.go
> +		mounts, err := ioutil.ReadFile(procFS)
Nit: os.ReadFile, ioutil is deprecated.

2021-11-02 09:07 UTC, lmb commented on examples/cgroup_skb/main.go
> +	bpfProgName        = "count_egress_packets"
Unused?

2021-11-02 09:08 UTC, lmb commented on examples/README.md
> +  * [cgroup_skb](cgroup_skb/) - Count the egress packets by attaching the program to the socket. It assumes cgroups2 file system was mounted at /sys/fs/cgroup/unified. If this is not true, run `sudo
From my recent ubuntu:
```
$ grep cgroup /proc/self/mounts
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
```

Works now, thanks!

2021-11-02 11:09 UTC, ti-mo requested changes
Thanks! Sorry this took so long to get to. A few small changes and this is good to go. :+1:

2021-11-02 11:09 UTC, ti-mo commented on examples/README.md
> +go run -exec sudo [./kprobe, ./uretprobe, ./ringbuffer, ./cgroup_skb, ...]
This extension is not needed, it's just to indicate how the examples can be run.

2021-11-02 11:09 UTC, ti-mo commented on examples/README.md
> +  * [cgroup_skb](cgroup_skb/) - Count the egress packets by attaching the program to the socket. It assumes cgroups2 file system was supported by your systems.
```suggestion
  * [cgroup_skb](cgroup_skb/) - Count packets egressing the current cgroup.
```

2021-11-02 11:09 UTC, ti-mo commented on examples/cgroup_skb/main.go
> +// The eBPF program will be attached as an egress filter for the socket to count the packets.
```suggestion
// The eBPF program will be attached as an egress filter, receiving an `__sk_buff` pointer for each outgoing packet.
```

2021-11-02 11:09 UTC, ti-mo commented on examples/cgroup_skb/main.go
> +	_, err = link.AttachCgroup(link.CgroupOptions{
The resulting `Link` object should always be defer-closed for good measure.

2021-11-02 19:06 UTC, mingleiw commented
@ti-mo @lmb  I've addressed all the comments. Thank you for the reviews!

2021-11-03 07:58 UTC, ti-mo approved these changes
Rebased and applied a few fixups. Thanks for your contribution! :tada:

2021-11-03 07:59 UTC, merged

2023-03-04 07:22 UTC, zhangzhiqiangcs commented
Hi, @ti-mo @mingleiw I just build and run this example, and got a err
```
loading objects: field CountEgressPackets: program count_egress_packets: load program: invalid argument
```
I tryed to print instructs and comes as
```
count_egress_packets:
          ; int count_egress_packets(struct __sk_buff *skb) {
         0: MovImm dst: r1 imm: 0
          ; u32 key      = 0;
         1: StXMemW dst: rfp src: r1 off: -4 imm: 0
         2: MovImm dst: r6 imm: 1
          ; u64 init_val = 1;
         3: StXMemDW dst: rfp src: r6 off: -16 imm: 0
         4: MovReg dst: r2 src: rfp
         5: AddImm dst: r2 imm: -4
          ; u64 *count = bpf_map_lookup_elem(&pkt_count, &key);
         6: LoadMapPtr dst: r1 map: Array(pkt_count)#3
         8: Call FnMapLookupElem
          ; if (!count) {
         9: JNEImm dst: r0 off: 9 imm: 0
        10: MovReg dst: r2 src: rfp
        11: AddImm dst: r2 imm: -4
        12: MovReg dst: r3 src: rfp
        13: AddImm dst: r3 imm: -16
          ; bpf_map_update_elem(&pkt_count, &key, &init_val, BPF_ANY);
        14: LoadMapPtr dst: r1 map: Array(pkt_count)#3
        16: MovImm dst: r4 imm: 0
        17: Call FnMapUpdateElem
        18: JaImm dst: r0 off: 1 imm: 0
          ; __sync_fetch_and_add(count, 1);
        19: StXXAddDW dst: r0 src: r6
          ; }
        20: MovImm dst: r0 imm: 1
        21: Exit
, invalid argument
2023/03/04 15:07:10 loading objects: field CountEgressPackets: program count_egress_packets: load program: invalid argument
```
Do you have any suggestions for the problems. Thanks for any help!

OS Version is Ubuntu 18.04

2023-03-04 12:08 UTC, zhangzhiqiangcs commented
sorry to bother. I found the reason is that my kernel version is too low.