prog: Allow empty data for prog.Test and prog.Run
cilium/ebpf pull request #685
Opened 2022-05-26 19:55 UTC by danobi

Certain prog types (SK_LOOKUP, RAW_TRACEPOINT and
RAW_TRACEPOINT_WRITABLE) require that data_in is NULL. The previous
check prevented 0 length data_in.

Fix by removing check.

Followup from #647.

2022-05-27 13:26 UTC, lmb requested changes
Could you add a test for this? AFAIR SK_LOOKUP programs will refuse to run if given DataIn, so you can use that to make sure this works.

2022-06-27 16:18 UTC, dxuuu commented
Ping

2022-06-28 21:06 UTC, ti-mo reviewed
Sorry for the long wait, there has been some PTO in between. Thanks for your patience! Left some minor comments.

2022-06-28 21:06 UTC, ti-mo commented on prog_test.go
> +		Data:    []byte{},
I think this could be removed, the call to `sys.NewSlicePointer(opts.Data)` in testRun() will return a `Pointer{}` whether Data is nil or length 0.

2022-06-28 21:06 UTC, ti-mo commented on prog_test.go
> +		Family: 2, /* AF_INET */
Feel free to add an entry to `internal/unix/types_*.go`.

2022-07-05 11:23 UTC, lmb commented on internal/cmd/gentypes/main.go
> +			"BpfSkLookup", "bpf_sk_lookup",
It's easier to automate generating names like `BtfInfo` vs capitalising some things.

2022-07-05 11:46 UTC, lmb approved these changes

2022-07-05 11:54 UTC, lmb commented
Sorry for the long delay, I wasn't aware that you had made changes and then I was busy with life when you pinged me. Thanks for following up :)

2022-07-05 11:54 UTC, merged