examples: add map in map example
cilium/ebpf pull request #696
Opened 2022-06-03 13:47 UTC by markpash

This example demonstrates the use of maps in maps in pure Go.
There's also use of the BPF_F_INNER_MAP flag which allows for
inner maps to be sized dynamically.

Signed-off-by: Mark Pashmfouroush <mark@isovalent.com>

2022-06-07 07:59 UTC, rgo3 approved these changes

2022-06-09 15:17 UTC, ti-mo requested changes
Some nits, very nicely explained. :rainbow:

2022-06-09 15:17 UTC, ti-mo commented on examples/map_in_map/main.go
> +			// Required for dynamically sized inner maps.
Might be worth quickly documenting as of which kernel version this works.

2022-06-09 15:17 UTC, ti-mo commented on examples/map_in_map/main.go
> +	// The outer map is created successfully and lives happily in the
:rainbow:

2022-06-09 15:17 UTC, ti-mo commented on examples/map_in_map/main.go
> +	var outerMapKey, innerMapID uint32
```suggestion
	var outerMapKey uint32
	var innerMapID ebpf.MapID
```
and remove the `ebpf.MapID` conversion in the call to `NewMapFromID`.

2022-06-09 17:28 UTC, markpash commented
I've addressed and resolved the nits.
I've also added a bit more verbosity to the comments, and fixed a bug I spotted.

2022-06-11 11:11 UTC, lmb approved these changes

2022-06-11 12:19 UTC, merged