Add IsPinned() to RawLink
cilium/ebpf pull request #817
Opened 2022-10-11 11:34 UTC by boratanrikulu

Map and Prog have IsPinned() func but RawLink doesn't have it. I added IsPinned() to RawLink. Also seems Unpin method of Rawlink doesn't have a test, I added it too.

2022-10-21 15:45 UTC, lmb requested changes
Thanks for the PR! Some nits, but otherwise good to go.

2022-10-21 15:45 UTC, lmb commented on link/link_test.go
> +	c := qt.New(t)
Can you change tests to use `qt.Assert` directly? `qt.New` might go away in the future.

2022-10-21 15:45 UTC, lmb commented on link/link_test.go
> +func mustCgroupFixtures(t *testing.T) (*os.File, *ebpf.Program) {
Can you leave the function where it was? It makes the diff larger than it has to be.

2022-10-21 15:45 UTC, lmb commented on link/link_test.go
> +func newRawLink(t *testing.T, cgroup *os.File, prog *ebpf.Program) (*RawLink, string) {
Nit: `newPinnedRawLink`

2022-10-21 15:45 UTC, lmb commented on link/link_test.go
> +	pinned := link.IsPinned()
What's the benefit of introducing a variable for `pinned`?

2022-10-21 17:32 UTC, boratanrikulu commented
@lmb, thank you for the review. I made updates

2022-10-24 08:59 UTC, ti-mo approved these changes
Thanks!

2022-10-24 08:59 UTC, merged